name: Build Docker Image
on:
  workflow_dispatch:

jobs:
  Build:
    name: Build Essentials
    runs-on: self-hosted
    steps:
      - name: Build - Build Base Docker Image
        run: |
          echo "=== Build start ==="   
          echo ssellu | sudo -S echo ""
          cd dockerfiles
          sudo docker build --force-rm -t "test:1.0" --build-arg BRANCH=${{ github.head_ref }} . -f d1.base.dockerfile
          echo "=== Build finished ==="
