name: CI

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-kinetic

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
         echo "=== Build start==="
         echo ${{ github.head_ref }}
        
         cd Dockerfiles
         docker build --force-rm --no-cache -f build.dockerfile -t "cpp-cv-project-template:base" --build-arg BRANCH=${{ github.head_ref }} . 
         echo "=== Build finished==="
         
      - name: Clean up Docker image if build fails
        if: failure()
        run: |
         echo "=== Remove failed image start==="
         docker rmi -f $(docker images -f "dangling=true" -q)
         docker images 
         echo "=== Removal finished==="
