name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  Build:
    name: Build Docker Image
    runs-on: self-hosted
    steps:
      - name: Build - Docker Image
        run: |
          eval $GET_REPO
          eval $GET_HASH
          echo "=== Build start ===" 
          cd dockerfiles
          sudo docker build --force-rm -f -t "${REPO}:${HASH}" --build-arg BRANCH=${{ github.head_ref }} . -f d1.base.dockerfile
          echo "=== Build finished ==="

