name: Run
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    container:
      image: test:1.2
    name: Pull & Rebuild
    steps:
      - name: Build ProSLAM
        run: |
          echo "=== Build ProSLAM ==="
          cd dockerfiles
          sudo docker build --force-rm -t --no-cache "test:1.2" --build-arg BRANCH=${{ github.head_ref }} . -f d3.build.dockerfile

      - name: Run ProSLAM
        run: |
          echo "=== Run ProSLAM ==="
          docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --name d2.run-app.dockerfile "test:1.2"
