name: Run ProSLAM - Dataset 00
on:
  workflow_dispatch:

jobs:
  job1:
    name: Run ProSLAM - Dataset 00
    runs-on: self-hosted
    container:
      image: ssellu/proslam:1.0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Build
        run: |
          echo "=== Build ProSLAM ==="
          ls -al
